"""empty message

Revision ID: 004672bb8495
Revises: 558b290c1a08
Create Date: 2021-04-21 12:03:37.947079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004672bb8495'
down_revision = '558b290c1a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['Cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favs')
    # ### end Alembic commands ###
